steps:
  # Build the Docker image with a unique tag using the commit SHA
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-a3/cloud-a3-c1:$COMMIT_SHA', '.']
  
  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-a3/cloud-a3-c1:$COMMIT_SHA']
  
  # Apply the deployment file to create/update PVC, Deployment, and Service
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'container1.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=preet-cluster'
  
  # Update the deployment to use the new image tag
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/container1-deployment', 'container1=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-a3/cloud-a3-c1:$COMMIT_SHA']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=preet-cluster'